version: '3.7'
services:
  mqtt-monitor:
    image: mqtt-monitor
    container_name: mqtt-monitor
    restart: unless-stopped
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./:/app
    network_mode: host